# Generated by Django 4.1.2 on 2022-12-06 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('chatroom_id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('chatroom_name', models.CharField(max_length=16, unique=True)),
                ('chatroom_passwd', models.CharField(max_length=32)),
                ('chatroom_about', models.CharField(default='', max_length=96)),
                ('chatroom_createTime', models.DateTimeField(auto_now_add=True)),
                ('chatroom_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('message_text', models.TextField()),
                ('message_createTime', models.DateTimeField(auto_now_add=True)),
                ('message_chatroom', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.chatroom')),
                ('message_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
