# Generated by Django 4.1.2 on 2022-12-06 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=16)),
                ('group_about', models.CharField(default='', max_length=96)),
                ('group_createTime', models.DateTimeField(auto_now_add=True)),
                ('group_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
