# Generated by Django 4.1.2 on 2022-12-06 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_message_message_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_chatroom',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.chatroom'),
        ),
    ]
