# Generated by Django 4.1.2 on 2022-12-06 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_alter_message_message_chatroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom_Admin',
            fields=[
                ('chatroomAdmin_id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('chatroomAdmin_admins', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('chatroomAdmin_chatroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chatroom')),
            ],
        ),
    ]
