# Generated by Django 4.1.2 on 2022-12-06 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_chatroom_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_owner',
        ),
        migrations.AddField(
            model_name='group',
            name='group_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Group_Admin_User',
            fields=[
                ('groupAdminUser_id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('groupAdminUser_chatroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.group')),
                ('groupAdminUser_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
