# Generated by Django 4.1.2 on 2022-12-07 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_privatechat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatechat',
            name='privatmessageTo_user',
        ),
        migrations.AddField(
            model_name='message',
            name='message_privatchat',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.privatechat'),
        ),
        migrations.AddField(
            model_name='privatechat',
            name='privatechatTo_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(default='', max_length=120)),
                ('privatechat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.privatechat')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
