# Generated by Django 4.1.2 on 2022-12-07 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_privatechat_privatmessageto_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message_privatchat',
        ),
    ]
