# Generated by Django 4.1.2 on 2022-12-07 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_message_message_privatchat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='privatechat',
        ),
    ]
