# Generated by Django 4.1.2 on 2022-12-07 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_user_profile_privatechat'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_privatchat',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.privatechat'),
        ),
    ]
