# Generated by Django 4.1.2 on 2022-12-07 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0015_chatroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_chatroom',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.chatroom'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=64)),
                ('group_about', models.CharField(default='', max_length=96)),
                ('group_createTime', models.DateTimeField(auto_now_add=True)),
                ('group_users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatRoom_Admin',
            fields=[
                ('chatroomAdmin_id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('chatroomAdmin_admins', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('chatroomAdmin_chatroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chatroom')),
            ],
        ),
    ]
