# Generated by Django 4.1.2 on 2022-12-07 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0016_message_message_chatroom_group_chatroom_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_Admin_User',
            fields=[
                ('groupAdminUser_id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('groupAdminUser_chatroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.group')),
                ('groupAdminUser_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
