# Generated by Django 4.1.2 on 2022-12-07 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_privatechat'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='privatechat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.privatechat'),
        ),
    ]
