# Generated by Django 4.1.2 on 2022-12-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_message_message_privatchat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='chatroom_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
