# Generated by Django 4.1.2 on 2022-12-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_chatroom_chatroom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom_admin',
            name='chatroomAdmin_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='group_admin_user',
            name='groupAdminUser_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='privatechat',
            name='privatechat_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
