# Generated by Django 4.1.2 on 2022-12-07 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_chatroom_admin_chatroomadmin_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group_admin_user',
            old_name='groupAdminUser_chatroom_id',
            new_name='groupAdminUser_group_id',
        ),
    ]
