# Generated by Django 4.1.2 on 2022-12-07 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_rename_groupadminuser_chatroom_id_group_admin_user_groupadminuser_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_chatroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.chatroom'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.group'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_privatchat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.privatechat'),
        ),
        migrations.AlterField(
            model_name='privatechat',
            name='privatechat_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
