# Generated by Django 4.1.2 on 2022-12-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_message_message_chatroom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='privatechat',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='privatechat',
            field=models.ManyToManyField(to='core.privatechat'),
        ),
    ]
