# Generated by Django 4.1.2 on 2022-12-07 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0027_rename_message_user_message_message_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_toUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_fromUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
