# Generated by Django 4.1.2 on 2022-12-14 06:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0028_message_message_to_alter_message_message_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='follow',
            field=models.ManyToManyField(related_name='follow_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
