# Generated by Django 4.1.2 on 2022-12-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_user_profile_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='profilePic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
