# Generated by Django 4.1.2 on 2022-12-15 17:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0030_user_profile_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='follow',
            field=models.ManyToManyField(blank=True, related_name='follow_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
